### PR TITLE
Enable Disco and Eoan and update README

### PR DESCRIPTION
**Pull request by ryan-beisner**

### CODE REVIEW

**Comment by ryan-beisner** [comment]
FYI:

```
ubuntu@juju-8d01b7-foo-0:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco
ubuntu@juju-8d01b7-foo-0:~$ sudo service zebra status
● zebra.service - GNU Zebra routing manager
   Loaded: loaded (/lib/systemd/system/zebra.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:zebra
ubuntu@juju-8d01b7-foo-0:~$ sudo service bgpd status
● bgpd.service - BGP routing daemon
   Loaded: loaded (/lib/systemd/system/bgpd.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:bgpd
ubuntu@juju-8d01b7-foo-0:~$ sudo service zebra start
ubuntu@juju-8d01b7-foo-0:~$ sudo service bgpd start
ubuntu@juju-8d01b7-foo-0:~$ sudo service zebra status
● zebra.service - GNU Zebra routing manager
   Loaded: loaded (/lib/systemd/system/zebra.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-09-05 18:36:31 UTC; 6s ago
     Docs: man:zebra
  Process: 13484 ExecStartPre=/sbin/ip route flush proto zebra (code=exited, status=0/SUCCESS)
  Process: 13497 ExecStartPre=/bin/chmod -f 640 /etc/quagga/vtysh.conf /etc/quagga/zebra.conf (code=exited, status=1/FAILURE)
  Process: 13498 ExecStartPre=/bin/chown -f quagga:quagga /etc/quagga/zebra.conf (code=exited, status=0/SUCCESS)
  Process: 13499 ExecStartPre=/bin/chown -f quagga:quaggavty /etc/quagga/vtysh.conf (code=exited, status=1/FAILURE)
  Process: 13500 ExecStart=/usr/sbin/zebra -d -A 127.0.0.1 -f /etc/quagga/zebra.conf (code=exited, status=0/SUCCESS)
 Main PID: 13501 (zebra)
    Tasks: 1 (limit: 2356)
   Memory: 1.2M
   CGroup: /system.slice/zebra.service
           └─13501 /usr/sbin/zebra -d -A 127.0.0.1 -f /etc/quagga/zebra.conf

Sep 05 18:36:30 juju-8d01b7-foo-0 systemd[1]: Starting GNU Zebra routing manager...
Sep 05 18:36:31 juju-8d01b7-foo-0 systemd[1]: Started GNU Zebra routing manager.
ubuntu@juju-8d01b7-foo-0:~$ sudo service bgpd start
ubuntu@juju-8d01b7-foo-0:~$ sudo service bgpd status
● bgpd.service - BGP routing daemon
   Loaded: loaded (/lib/systemd/system/bgpd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-09-05 18:36:34 UTC; 12s ago
     Docs: man:bgpd
  Process: 13533 ExecStartPre=/bin/chmod -f 640 /etc/quagga/bgpd.conf (code=exited, status=0/SUCCESS)
  Process: 13541 ExecStartPre=/bin/chown -f quagga:quagga /etc/quagga/bgpd.conf (code=exited, status=0/SUCCESS)
  Process: 13542 ExecStart=/usr/sbin/bgpd -d -A 127.0.0.1 -f /etc/quagga/bgpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 13547 (bgpd)
    Tasks: 1 (limit: 2356)
   Memory: 2.4M
   CGroup: /system.slice/bgpd.service
           └─13547 /usr/sbin/bgpd -d -A 127.0.0.1 -f /etc/quagga/bgpd.conf

Sep 05 18:36:34 juju-8d01b7-foo-0 systemd[1]: Starting BGP routing daemon...
Sep 05 18:36:34 juju-8d01b7-foo-0 systemd[1]: Started BGP routing daemon.
ubuntu@juju-8d01b7-foo-0:~$ 
```

**Comment by ryan-beisner** [comment]
Confirmation with this branch deployed:

```
ubuntu@beisner-bastion:~/git/charm-quagga$ juju status quagga-disco
Model  Controller           Cloud/Region             Version  SLA          Timestamp
foo    beisner-serverstack  serverstack/serverstack  2.6.9    unsupported  18:43:46Z

App           Version  Status  Scale  Charm   Store  Rev  OS      Notes
quagga-disco           active      1  quagga  local    2  ubuntu  

Unit             Workload  Agent  Machine  Public address  Ports  Message
quagga-disco/0*  active    idle   0        10.5.0.20              Ready (AS Number 4211408915)

Machine  State    DNS        Inst id                               Series  AZ    Message
0        started  10.5.0.20  a91d5e9a-fff1-48f3-87fb-728e2eb19c53  disco   nova  ACTIVE
```

**Comment by ryan-beisner** [comment]
```
ubuntu@beisner-bastion:~/git/charm-quagga/builds/quagga$ juju status quagga-eoan
Model  Controller           Cloud/Region             Version  SLA          Timestamp
foo    beisner-serverstack  serverstack/serverstack  2.6.9    unsupported  19:01:04Z

App          Version  Status  Scale  Charm   Store  Rev  OS      Notes
quagga-eoan           active      1  quagga  local    0  ubuntu  

Unit            Workload  Agent  Machine  Public address  Ports  Message
quagga-eoan/0*  active    idle   10       10.5.0.26              Ready (AS Number 4211408921)

Machine  State    DNS        Inst id                               Series  AZ    Message
10       started  10.5.0.26  1948a0a0-bd02-4532-a145-20c70fe04267  eoan    nova  ACTIVE
```

**Review by camille-rodriguez — COMMENTED** [review]
LGTM

**Review by camille-rodriguez — APPROVED** [review]
LGTM

**Pull request merged**
